# Introduction

Over the past twenty years, economic theorists have become increasingly aware of the fact that many economic problems can be usefully analyzed by explicitly considering the nature of actors' limited information and the role that economic institutions play in shaping outcomes through affecting actors' incentives and strategic behavior. Information economics and game theory have had a major impact on economists' view of almost all branches of economics. As part of this over-all ferment of ideas and research, theorists have devoted considerable attention to analyzing incentive contracting problems that arise in the study of public procurement, private procurement, regulation, the theory of the firm, the theory of organizations, and managerial compensation. Many of the same abstract themes and ideas arise in all of these areas and, in fact, many of these abstract topics and themes have become distinct subjects of study themselves. Even the number of theory papers analyzing defense procurement per se is quite large. However, the entire literature analyzing models relevant to defense procurement is many times larger. The purpose of this chapter is to provide an introduction to the incentive models literature that is relevant to defense procurement.

Government undeniably faces an incredibly complex and multi-faceted incentive problem in military procurement. Defense firms have private information and not all their actions can be monitored. Huge uncertainties pervade the process and complete long-term contracts are generally impossible to write and difficult to enforce. Much of the procurement process occurs in a situation of bi-lateral monopoly and both sides of the market are wary of making specific investments that will reduce their bargaining power. R&D is a key output of the process and the inherent difficulty of objectively measuring the quality of new ideas adds immeasurably to the incentive problem. Finally, on top of everything else, "government" in reality is not a single rational actor, but is itself a complex hierarchical institution, and incentive problems between actors within government are important in themselves and also impact the way that government is able to interact with defense firms.

A number of excellent surveys and overviews exist that are complementary to this one. Less technical discussions of incentive models and their role in explaining defense procurement are contained in Baron (1993), Rogerson (1994) and Sandler and Hartley (1995). Discussions of incentive models more generally, with no particular focus on defense procurement are contained in Baron (1989), Besanko and Sappington (1987), Caillaud et al. (1988), and Sappington (1991). A more thorough textbook-like treatment of many of the models discussed in this chapter is contained in Laffont and Tirole (1993). A classic discussion of incentives in procurement that predates the modern incentives literature, and is still well worth reading, is by Scherer (1964).

This chapter will rely on the American procurement system as a source for stylized facts and observations about real behavior. Since the nature of the procurement problem and the procurement system in place is very similar across the United States and most other Western countries, most of the conclusions of this chapter apply equally well to the procurement systems in other Western countries. However, there are some differences. In general, other countries have smaller domestic markets, and rely to a greater extent on joint ventures with other countries, imports, and international sales. See Sandler and Hartley (1995) for a more complete discussion of other countries' procurement systems and how they compare to the US system.

This chapter proceeds as follows. Section 2 provides an economic overview of important features of the procurement problem and the procurement process. Sections 3 and 4 describe models of a stylized one-shot procurement problem that will be called the simple procurement problem (SPP). Section 3 considers the case of a single agent and Section 4 considers the case of multiple agents. Since much of the incentives literature consists of variants of the basic models described in Section 3 these models are discussed in considerable detail. Section 5 considers R&D, and Section 6 considers multiple periods of production. All of the preceding sections focus on the incentive problem between government and defense firms. Section 7 broadens the scope of the analysis to consider incentive problems within government.
