# Background[^1]

[^1]: This section draws on @Rogerson1994.

## Introduction

The incentive problem between government and defense firms is shaped by four underlying economic characteristics. This section will begin by describing these four characteristics and then go on to discuss some of their consequences for procurement policy. 

## Characteristic #1: Research and development 

A defining characteristic of weapons procurement is the constant pursuit of improved performance and capabilities through technological advance. Thus, innovation is at least as important a product of the defense sector as the physical products that embody the new ideas. As will be argued below, innovation is an inherently difficult product to purchase, and this creates the need for providing incentives for innovation. 

## Characteristic #2: Uncertainty 

Massive uncertainties permeate the procurement process. @PeckScherer1962 and @Scherer1964 distinguish between internal and external uncertainty. Internal uncertainty is uncertainty due to technological unknowns and is especially high in the design phase of a new weapon. However, even after production begins, most products continue to evolve in order to incorporate new technologies, fix unanticipated problems, etc. Thus, major uncertainties about cost and design typically continue into production. External uncertainty is uncertainty in the demand for a weapon due to changes in the external threat, changes in the availability of substitute weapons, or simply changes in Congress's willingness to purchase certain weapons. As events of the early 1990s make abundantly clear, external uncertainties are also enormous for most weapons systems. 

A major consequence of these large uncertainties is that the Department of Defense (DoD) typically does not find it feasible or desirable to sign long-term fixed-price production contracts. In the design phase, the ultimate nature of the final weapon is not yet known. Even after production begins, the weapon will continue to evolve in unanticipated ways and DoD's demand will change in unanticipated ways. Thus long- term fixed-price contracts for the entire decade or more long production run typical of most weapons systems are thought to be infeasible[^2] DoD's failed attempt to use such contracts in the 1960s (which was referred to as the total package procurement approach) is generally thought to have conclusively demonstrated the infeasibility of this approach [@BurnettScherer1990]. Rather, production contracts are signed for one annual lot of production at a time on an annual basis. In fact, these same uncertainties typically mean that even fixed-price annual contracts are difficult to fully enforce. Unanticipated changes almost always occur and these result in substantial renegotiations during the life of the contract.

[^2]: Note that the possibility of unanticipated price inflation is not generally a major problem. This can be, and is, dealt with fairly well through using inflation adjustment formulas based on price indices for various industrial products. It is the fundamental uncertainty over the nature of the product and the demand for it that prevents the use of long-term contracts.

## Characteristic #3: Economies of scale in production

Within most sectors of the defense industry, there are multiple firms that would be capable ex-ante of designing and producing a given weapons system. Therefore economies of scale do not appear to preclude the existence of multiple competitors at the beginning of a program. Furthermore, design expenditures are relatively small in the early phases of a program, and, given uncertainties at the design stage, it is often sensible to pursue multiple design strategies since it is not clear which will work best. The result is that DoD very typically funds two design approaches through to the stage where prototypes are built. Thus, economies of scale do not preclude the existence of competition through to the end of the design phase. 

However, production is another matter. Given the relatively small quantities purchased of most weapons systems, it is generally thought to be completely uneconomic to have multiple firms produce the same weapon system. Furthermore, the same reasoning implies that it is uneconomic to have two or three designs enter production that are relatively good substitutes for one another, and to buy some of each. Dramatic cost reductions could generally be achieved by purchasing larger quantities of only one design. Therefore, it is generally the case that production of almost all major weapons systems occurs in a sole source environment. Although the existence of mild substitutes may create some competitive pressures in some cases, there will not typically be a close substitute for any major system and thus the effect of competition between substitutes is limited. 

The major implication of this is that prices cannot be competitively determined. As explained above, at the end of the design phase when there is still competition, pervasive uncertainties prevent the signing of a single production contract for the entire production run. Thus the bulk of all production contracts will be negotiated with a sole source. 

Government's response to this has been to base prices on estimated costs. A fixed price is typically negotiated for each annual production lot. However, the fixed price is determined largely by historic and projected accounting costs, both of which are carefully and meticulously audited. A "profit" term is also added to compensate firms for the cost of capital and risk-bearing [@Rogerson1992economic]. Thus, during the production phase, the sole source producer operates much as does a regulated utility with a fairly similar type of incentive for cost efficiency. If it manages to find a new way to lower its costs, it will keep the benefit for the current production but government will eventually receive the benefit when new prices for future production are negotiated. 

Even the extent to which annual fixed-price contracts are truly fixed price is open to question. Under the Truth in Negotiations Act (TINA), defense contractors must submit detailed "current accurate and complete" cost estimates when they negotiate the price of a contract with DoD. Firms that achieve large unpredicted cost reductions therefore expose themselves to a significant risk of prosecution for failing to reveal all they knew at the time of the negotiation. In this way, TINA converts a fixed-price contract into something more closely resembling a cost-reimbursement contract [@Kovacic1991].

## Characteristic #4: Government is the sole buyer

Government is the only possible buyer of most weapons[^3] Furthermore, many of the technologies and skills required to create and produce weapons systems are relatively specific to the weapons industry. The main consequence of this is that it creates a major hold-up problem [@Williamson1985]. At the R&D phase, firms may worry that if they invest their own funds to create ideas for weapons systems, they will never recover these sunk expenses. At the production phase, firms may worry that they will never recover their investments in physical capital which has little use outside the defense industry. More generally, one of the main assets of any defense firm is its human capital embodied in the knowledge and working relationships of its design team members. Firms may worry that expenditures to create better design teams will never be recovered since there is no good alternative use for this asset. 

Government has responded to firms' fears to invest in specific assets in three ways. First, it has become a purchaser of the intermediate product "R&D", as well as the final product, "functioning weapons systems". That is, government directly funds a large portion of defense-related R&D. In most purely commercial markets, consumers of course do not purchase R&D. Rather they only purchase final products if they value the results of the R&D as embodied in the product. One reason for this is that the direct purchase of R&D is complicated by difficult incentive problems. Thus, by responding to the hold-up problem and directly funding R&D, government has created a new incentive problem for itself. How can it induce defense firms to perform good R&D? 

Second, it has become the purchaser of many specific physical assets for defense firms. Physical assets that cannot be easily adapted to other weapons programs are termed "special tools and test equipment" and these are purchased directly by government. Although statistics are very difficult to come by, I am told by informed industry and government sources that the dollar value of such government funded capital is often very large and is comparable to the dollar value of firm funded capital. As well, the government sometimes provides contractual guarantees that capital will be paid for if a program is canceled (e.g., the B1 and B2) or literally builds and owns the entire physical plant (e.g., the F16). However, these latter practices are more rare. 

Third, through a massive set of regulations and policies, DoD has established an extra-contractual administrative relationship with firms that provides them with a range of guarantees that their specific investments will not be appropriated [@CrockerReynolds1993; @Goldberg1976]. Perhaps the major such regulatory guarantee is the regulatory directive that prices will be cost-based when negotiations occur with a sole source. That is, procurement regulations specifically instruct contracting officers negotiating with a sole source that their job is not to obtain the lowest price. Rather, regulations instruct them in great detail how to calculate a fair price based on estimated costs and instruct them to obtain this price. The fair price also includes a "profit" term which is meant to reimburse firms for the cost of capital, the cost of risk-bearing and other economic costs not recognized as costs by the accounting system [@Rogerson1992economic]. Many of the cost elements that the regulations instruct contracting officers to pay for are likely to be sunk at the time of negotiation. 

There is a distinct element of reputational enforcement inherent in this relationship. Some of the DoD behavior that provides investment guarantees is simply DoD practice and not mandated by any regulation. Even behavior mandated by regulations cannot be completely relied on because regulations can be changed. Of course, it can be difficult to change regulations, especially when defense firms can directly lobby Congress to intervene, etc. This difficulty in changing regulations works to DoD's advantage in convincing firms that they can rely on the regulations. Nonetheless, there is also an element of reputational enforcement. Namely, DoD would often benefit in the short run from reneging on all of its commitments and negotiating the lowest possible prices for the current period's prices. However, in the long run, DoD would be harmed because it would no longer be able to convince firms to engage in specific investments. Thus, it may well be rational for DoD to honor its implicit commitments as codified in its regulations.

[^3]: The government strictly regulates foreign sales SO can be viewed as exercising control over these sales as well.

## The program life cycle

Based on the above discussion, we can view the life cycle of a program as being divided into three phases. First is the design phase, during which multiple firms pursue competing designs. In early portions of the design phase there may be five or more firms; however, by the end of this phase, DoD is usually left with two competing firms, each with its own design. DoD directly funds most of this research through cost- reimbursement contracts. However, competition for the production franchise is often intense and thus firms often augment DoD funding with their own private funds. 

The second phase is the sole source selection phase, in which firms submit prototypes, final design plans, etc. to DoD SO it can evaluate the relative merits of the designs. They also typically bid on the next increment of work, which consists of finalizing the design, establishing the production line, and producing the first few items. DoD selects a winner based on its evaluation of the competing designs (their likely performance, production cost, maintainability, etc.) and the bids on the next increment of work. A single winner is chosen because of economies of scale. 

The third phase is the production phase, during which the winner of the source selection phase produces the product. This phase may last a decade or more. An important point is that almost all of the production contracts are signed in a sole source environment after the winner has been chosen, because of cost uncertainties, demand uncertainties, and the evolving nature of the product. Prices in the production phase are highly cost based. Although production occurs under a series of annually signed fixed-price contracts, each contract's price is largely determined by audited historic and audited projected accounting costs. Furthermore, strict application of TINA probably even makes each annual fixed-price contract more cost-based than a true fixed-price contract.

## Discussion

An interesting perspective on the role of the above four characteristics in generating the regulatory problem of defense procurement can be obtained by considering how the regulatory problem would change if only some were true. In particular, it is illuminating to consider the first two features as one group (R&D is important; large uncertainties) and the second two as a separate group (large economies of scale in production imply the absence of close substitutes; government is sole purchaser). 

Suppose that only the first group of features was true. This would be an industry where technological advance is rapid and important and where large uncertainties exist, especially at the R&D phase. However, government is not the only buyer and economies of scale are not SO large as to preclude competition between substitutes. The obvious example of such an industry is the computer industry. Computer procurement works in a completely different fashion than weapons procurement [@Kelman1990]. The government does not directly buy R&D; rather, it buys final products much as occurs in any normal commercial market. Furthermore, it does not directly fund facilities capital investments. Finally, procurement is usually accomplished through competitive bidding with no element of cost based pricing. Now suppose that only the second group of features was true. This would be an industry where technological advance is not particularly important and thus efficient production is the only real issue. However, there are large economies of scale SO there is room in the market for only one firm. This is, of course, the description of a traditional public utility regulation problem. Thus, in some sense, the production phase of a procurement problem can be viewed as a typical public utility problem. What makes defense procurement special, is that each franchise lasts only a decade or so, and firms compete for the franchise by performing R&D. Furthermore, generating the correct amounts of the correct types of R&D is a major goal of the regulatory system.

## Theory of the internal organization of the firm

One feature that distinguishes defense procurement from traditional public utility regulation is that each production program can be viewed as its own franchise and thus ex-ante competitions for each franchise are generally possible. This feature means that the regulatory problem in defense is much more closely related to incentive issues that arise in the theory of the firm than is the standard regulatory problem. In particular, DoD's long-term relational partnerships with suppliers are similar, in some respects, to the type of relationships that large commercial firms such as General Motors, have with their major suppliers. Production of major automobile subcomponents or parts often requires specific investments in R&D or physical capital. Production often occurs by a single source. However, the relationship is nested in a larger competitive environment where GM could turn to different subcontractors for future programs if it wished. Thus, just as in defense procurement, sole source relationships with specific investments occur in the context of a larger competitive environment for future programs. 

One of the major differences between the DoD problem and GM's problem regards the "make versus buy" decision. Many observers believe that government either lacks the ability to take production in-house (due to low civil service pay scales, cumbersome personnel systems, lack of flexibility for decision-making, etc.), or simply does not want to design and produce its own weapons because of an ideological preference for private enterprise[^4]. If this is true, then the government's options to make instead of buy are much more limited than GM's. This difference is interesting, because, as will be discussed further in the next two sections, a major problem faced by the defense regulatory system is how to provide incentives for R&D. There is some evidence that large commercial firms deal with this problem by moving production in- house. @MonteverdeTeece1982 show that large automotive firms are much more likely to produce a component in-house if it involves large amounts of R&D. This suggests that provision of incentives for R&D may be a particularly difficult problem in purchaser/supplier relationships.

[^4]: The fact that state ownership of defense firms is fairly common in Europe perhaps suggests that the latter reason (ideological preference) may be more important than the former (technological infeasibility).

## Prizes for innovation

A recurring theme in the above discussion is the necessity for providing incentives for innovation. This part will explain how the current system provides these incentives. An important characteristic of the R&D stage is that the output of this stage is inherently difficult or impossible to measure objectively and describe for purposes of contracting. That is, it is essentially impossible to sign explicit incentive contracts at the R&D stage that specify all possible good ideas and the reward that the firm will be paid as a function of which good idea it comes up with. The obvious objectively verifiable signal of whether a firm has created a successful new weapons design is whether DoD chooses to purchase it. Thus, a regulatory system could create prizes for innovation by guaranteeing that firms which generate ideas good enough to be adopted by the government will receive prizes in the form of economic profit on the production phase of the system. Furthermore, if profit was awarded approximately as a percentage of cost, this might also tend to award larger prizes to more important innovations, at least in a rough sense. 

This is, in fact, the approach that DoD appears to follow. The overall result of DoD's regulatory system is that a defense firm selected to be sole source producer of a weapons systems earns economic profit on the production phase of the program and the prospect of earning this sole source profit gives defense firms an incentive to exert their best efforts at the design phase. Two different approaches have been used to empirically estimate the size of this effect @Rogerson1989 and @Rogerson1991profit  uses an event study methodology to estimate the size of the prizes that winners of design contests earn and finds that it is equal to approximately 3.3% to 4.7% of revenues earned in the production phase. @Lichtenberg1998 directly estimates the effect of government business on defense firms' private R&D expenditures and finds that one dollar of production purchases may stimulate 54 cents of such expenditures.

## Inter-linked stages

An extremely important feature of the procurement process is that firms' behavior is interconnected across the three stages of procurement: design, sole source selection, and production. This means that models of the procurement process which focus on only one of the stages may fail to capture important aspects of the problem. In general, one must approach procurement policy by simultaneously considering behavior and policy options at all three stages. For example, government might choose to influence the overall amount and quality of R&D by varying direct funding at the design phase, by taking steps to change the competitiveness of bidding at the source selection phase, or by changing the profitability allowed during sole source production. Of course, these tools will have different effects on other goals, like efficiency at the production stage. Thus, an optimal policy must be designed by identifying how different combinations of policies at different stages affect all the goals to be achieved. 

For some important questions, it is necessary to expand the scope of analysis even further, to include multiple programs. This is because economies of scope exist across products [@Rogerson1992overhead] and because award decisions made today will influence the nature of the industrial structure that exists tomorrow, and thus affect the range of options open to government in the future. Therefore, links between stages of a program and links between programs often have critically important effects, and this must be kept in mind when interpreting the results of models that limit themselves to a single stage of the process or a single program.
